# -*- coding: utf-8 -*-
POSTS_PER_PAGE = 5
POST_CONTENT_ON_HOMEPAGE = True
ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = 'pbkdf2:sha1:1000$lWE2H2fO$feab21b7d6fd86355414a0de5b31cf9ea07f8d94'
ANALYTICS_ID = ''
GITHUB_USERNAME = 'jacobthill'
CONTACT_EMAIL = 'jacobhill.mail@gmail.com'
BLOG_TITLE = ''
BLOG_TAGLINE = ''
BLOG_URL = '/'
FONT_NAME = 'Source+Sans+Pro'
SECRET_KEY = '7GPBQLVZGC4DGHUPBD5AGJSRE2RHVUZQIHCLG7KKHUS5ZUYRPYJA===='
DISQUS_SHORTNAME = ''
USE_ADDTOANY = True
USE_SUBTOME = False
