# -*- coding: utf-8 -*-
POSTS_PER_PAGE = 5
POST_CONTENT_ON_HOMEPAGE = True
ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = 'pbkdf2:sha1:1000$pKykDhZ7$2d22e0d45755c96dab43436961fd4655cbd33f26'
ANALYTICS_ID = ''
GITHUB_USERNAME = 'jacobthill'
CONTACT_EMAIL = 'jacobhill.mail@gmail.com'
BLOG_TITLE = 'Introduction to NLP'
BLOG_TAGLINE = ''
BLOG_URL = '/'
FONT_NAME = 'Source+Sans+Pro'
SECRET_KEY = '5SOPNUUH2G52BHOCNVS6IRZIDRQKEKTKGGCZ3NJLRCB7XHDBLK5A===='
DISQUS_SHORTNAME = ''
USE_ADDTOANY = True
USE_SUBTOME = False
